name: colored_print
description: This package makes it possible to use colored prints.
version: 1.0.0
homepage: https://github.com/davidsdearaujo/colored_print

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  test: ^1.17.10